# Generated by Django 4.2.3 on 2023-07-31 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='end_date',
        ),
    ]
